repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff
        args: [--fix]

  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy
        args: [--ignore-missing-imports]
        language_version: python3
        additional_dependencies:
          - types-requests
          - types-PyYAML

  - repo: local
    hooks:
      - id: pytest-windows
        name: Run Pytest (Windows)
        entry: powershell -ExecutionPolicy Bypass -File hooks/pre-commit-pytest.ps1
        language: system
        types: [python]
        exclude: ^\.github/
        platforms: [windows]

      - id: pytest-linux
        name: Run Pytest (Linux/CI)
        entry: hooks/pre-commit-pytest.sh
        language: system
        types: [python]
        exclude: ^tests/test_ocr.py
