line-length = 100
target-version = "py311"
select = ["E", "F", "I", "UP", "B"]
ignore = ["E501"]
exclude = ["__pycache__", "tests/test_ocr.py"]

[isort]
known-first-party = ["backend"]
combine-as-imports = true
force-wrap-aliases = true
