line-length = 100
target-version = "py311"
exclude = ["__pycache__", "tests/test_ocr.py"]

[lint]
select = ["E", "F", "I", "UP", "B"]
ignore = ["E501", "F401", "F403", "F841"]

[lint.isort]
known-first-party = ["backend"]
combine-as-imports = true
force-sort-within-sections = true
