name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies and set PYTHONPATH
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"
          echo "PYTHONPATH=${{ github.workspace }}" >> $GITHUB_ENV  # ✅ move here

      - name: Write test .env
        run: echo "ACTIVE_APP=concierge" > .env
             echo "OPENAI_API_KEY=test-key" >> .env

      - name: Run tests
        run: |
          pytest
