name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Prepare environment
        run: |
          echo "ACTIVE_APP=concierge" > .env
          echo "OPENAI_API_KEY=test-key" >> .env

      - name: Lint with Ruff
        run: |
          ruff check .

      - name: Type-check with Mypy
        run: |
          PYTHONPATH=${{ github.workspace }} mypy backend tests

      - name: Run tests (internal only)
        run: |
          echo "ACTIVE_APP=concierge" > .env
          echo "OPENAI_API_KEY=test-key" >> .env
          PYTHONPATH=${{ github.workspace }} pytest -m "not external"
