name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}  # 👈 FIX: sets PYTHONPATH for all steps

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Write test .env
        run: echo "ACTIVE_APP=concierge" > .env  # 👈 FIX: prevent RuntimeError in gpt_engine

      - name: Run tests
        run: |
          pytest
