name: Run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}
      ACTIVE_APP: concierge
      OPENAI_API_KEY: fake-ci-key

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ".[dev]"

      - name: Lint with Ruff
        run: ruff check .

      - name: Type-check with Mypy
        run: mypy backend tests

      - name: Run tests (internal only)
        run: pytest -m "not external"
